### ISSUE TITLE
message handling 

### ISSUE THREAD

**Issue by DiptoChakrabarty** [CodeChefVIT/Quizzie#105]
On organiser or student login if forgot password is used and unregistered email id is provided , error message returned is 

' Reset code could not be sent' 

We should return a meaningful message instead which tells user to register themselves first

**Comment by quizhpi** [comment]
@DiptoChakrabarty I'll gladly make the update.

**Comment by DiptoChakrabarty** [comment]
Sure @quizhpi please go ahead
