### ISSUE TITLE
global variable for verifyURL

### ISSUE THREAD

**Issue by RishabhKodes** [CodeChefVIT/Quizzie#108]
[https://github.com/CodeChefVIT/Quizzie/blob/master/Backend/api/routers/user.js](https://github.com/CodeChefVIT/Quizzie/blob/master/Backend/api/routers/user.js)

Make a global variable in the code for `verifyURL` or define it in .env.

The repeated use of the same string for the same variable is not a good practice for a clean code.

**Comment by saaheel** [comment]
Can you assign it to me, I will try to fix this

**Comment by DiptoChakrabarty** [comment]
> Can you assign it to me, I will try to fix this

Sure @saaheel  go ahead

**Comment by saaheel** [comment]
Thanks, I will be on it

**Comment by jugaldb** [comment]
@saaheel  any updates?

**Comment by nanipunepalle** [comment]
Can I fix this @jugaldb

**Comment by jugaldb** [comment]
@akshatvg can we assign this to @nanipunepalle

**Comment by akshatvg** [comment]
Due to inactivity by the original assignee, I’ve assigned you now @nanipunepalle ✌🏻

**Comment by nanipunepalle** [comment]
Ok @akshatvg will make a PR soon

**Comment by nanipunepalle** [comment]
@akshatvg  added middleware with verifyurl  and updated all routes according to it here https://github.com/nanipunepalle/Quizzie/blob/1c07c82fd5f8913f30fc2a63e498318242b8e765/Backend/api/middleware/verifyURL.js#L1

**Comment by jugaldb** [comment]
You can close the issue after merging @akshatvg  refer: [#115](https://github.com/CodeChefVIT/Quizzie/pull/115)
