### ISSUE TITLE
Linting for backend

### ISSUE THREAD

**Issue by YashMeh** [CodeChefVIT/Quizzie#110]
### Issue 
The backend code does not have any clear formatting .
### Fix  
Add Eslint + Prettier for better code formatting.
### Expected behaviour :be
Auto lint and format on commit

### References 📖 
[EsList and Prettier](https://medium.com/javascript-scene/streamline-code-reviews-with-eslint-prettier-6fb817a6b51d#:~:text=ESLint%20performs%20automated%20scans%20of,quotes%20vs%20double%20quotes%2C%20etc.)

**Comment by christianto88** [comment]
Hi. I would like to take this task

**Comment by YashMeh** [comment]
Cool go ahead !

**Comment by christianto88** [comment]
@YashMeh do u have any specific rules for prettier?

**Comment by YashMeh** [comment]
@christianto88 thank you for asking, use the defaults for now, we can always play around IMO.

**Comment by christianto88** [comment]
@YashMeh hi ,i cannot push changes to this repo

**Comment by YashMeh** [comment]
@christianto88 , what exact procedure are you following ?

**Comment by akshatvg** [comment]
@christianto88 did you fork the repo first? You'll need to push to your forked repo and then send a PR.

**Comment by christianto88** [comment]
@akshatvg @YashMeh Hi sorry for the inconvenience. I have made a PR on this issue

**Comment by YashMeh** [comment]
closed via #111
