### ISSUE TITLE
Add functionality for adding quiz images

### ISSUE THREAD

**Issue by jugaldb** [CodeChefVIT/Quizzie#114]
By quiz images i mean the overall quiz image not images within the question, this can act as a thumbnail for the quiz ,both frontend and backend changes would be required.

**Comment by r0hnx** [comment]
I would like to work on this.

**Comment by jugaldb** [comment]
@akshatvg  can you mark this as Hacktober fest and assign?

**Comment by akshatvg** [comment]
@r0hnx I’ve assigned you to it.

**Comment by jugaldb** [comment]
@r0hnx any updates??

**Comment by akshatvg** [comment]
@r0hnx I'm removing you as an assignee as there's been no updates for a long time. This issue is once again open for anyone to work upon. @jugaldb you can also finish it.

**Comment by jugaldb** [comment]
Cool, I'll work on it soon, if anyone wants it to be assigned to them before I do, please do so, I will let you know when I start. @akshatvg 

edit: We would need someone from frontend to work on this as well @akshatvg

**Comment by akshatvg** [comment]
@Sarthakbh321 and @jugaldb work on this.

**Comment by akshatvg** [comment]
@jugaldb and @Sarthakbh321 any updates?

**Comment by jugaldb** [comment]
Since this feature doesnt seem to be useful enough, closing this issue
