### ISSUE TITLE
revert the last merge of node-cron

### ISSUE THREAD

**Issue by jugaldb** [CodeChefVIT/Quizzie#117]
hi @decipher07  did you run and test the /start route once, the function looks correct but it throws error when we run it,

screenshot of logs: 
![image](https://user-images.githubusercontent.com/55304795/97204210-d2fced80-17db-11eb-9762-53004ff6510b.png)

@akshatvg  we need to revert this change.

**Comment by jugaldb** [comment]
@decipher07 , if it worked for you, can you share a [screen recording](veed.io/screen-recorder)

**Comment by jugaldb** [comment]
Perhaps you can share a screen recording if it works for you @decipher07

**Comment by akshatvg** [comment]
@decipher07 any updates?

**Comment by decipher07** [comment]
Just looked at this today, I will start up with this.

**Comment by akshatvg** [comment]
@decipher07 @jugaldb any updates?

**Comment by jugaldb** [comment]
I thought @decipher07 was working on this.
