### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by EloFran** [CodeChefVIT/Quizzie#121]
Hi all,

I would like to know how I change the credentials so that when I use the login it does not redirect me to your login.

thx

**Comment by jugaldb** [comment]
Hey @EloFran,  the way I understood your issue is that you want to change the redirect link of Google auth, 

Steps
1. Go to routes/auth.js and same for admin auth
2. You would see a redirect url, just change it from quizzie.codechefvit.com to whatever you want it to redirect to
3. Make sure your Google console settings are proper.
Follow  https://link.medium.com/0K9oFVu5ibb to know about Google oauth in detail

I hope this clarifies it, let me know if you me to add anything else.

Thanks.

**Comment by EloFran** [comment]
thx for reply,

When i type `npm run dev` it return, is it normal?

```
[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
C:\Users\eloyf\Desktop\VUE\GOOGLE\Quizzie-master\Quizzie-master\node_modules\passport-oauth2\lib\strategy.js:86
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                           ^

TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (C:\Users\eloyf\Desktop\VUE\GOOGLE\Quizzie-master\Quizzie-master\node_modules\passport-oauth2\lib\strategy.js:86:34)
    at new Strategy (C:\Users\eloyf\Desktop\VUE\GOOGLE\Quizzie-master\Quizzie-master\node_modules\passport-google-oauth20\lib\strategy.js:52:18)
    at Object.<anonymous> (C:\Users\eloyf\Desktop\VUE\GOOGLE\Quizzie-master\Quizzie-master\Backend\api\config\passport-setup.js:27:14)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\eloyf\Desktop\VUE\GOOGLE\Quizzie-master\Quizzie-master\app.js:5:23)    
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
[nodemon] app crashed - waiting for file changes before starting...
```

the only way I can get it to work is by doing `npm install` in **root**, then` npm install ` in **/frontend**. Then `npm run dev` in **root** and then `npm run start` in **/frontend**. But it keeps redirecting me at your auth...

![image](https://user-images.githubusercontent.com/37640520/98737336-5b67ba80-23a6-11eb-90d2-9cc17c4b774c.png)

It is my localhost:3000

**Comment by jugaldb** [comment]
The backend and the frontend are completely different, to run backend you need to use _npm run dev_ in the **root** and for frontend you need to build it and then run it as per the package json in the frontend folder, also this error is normal as you don't have a .env file created, you will need to have some .env credentials of your own to get started, let me create a list of all the variables you will need to add.

@Sarthakbh321 please do explain the front-end part as well, 


Also for the redirect url as I mentioned in my first comment you will need to change the redirect url inside of Backend/api/routes/auth.js 

Change _quizzie.codechefvit.com_ to your URL

Lemme create a list of all the env keys and stuff you will need.


So what you got as output was completely logical to happen as you don't have a .env file and you don't have all the variables created for it, lemme get a list of all the variables asap

**Comment by jugaldb** [comment]
@EloFran 

Go to https://github.com/CodeChefVIT/Quizzie/blob/master/Backend/api/routers/auth.js
And 
https://github.com/CodeChefVIT/Quizzie/blob/master/Backend/api/routers/auth-admin.js

in both the cases change the res.redirect url as shown in the screenshot below 
![Screenshot_20201111-071047](https://user-images.githubusercontent.com/55304795/98754712-45311d00-23ed-11eb-9145-68c9b3ff8f46.jpg)



I hope this makes sense

**Comment by jugaldb** [comment]
dbURI
jwtSecret
clientID

**Comment by jugaldb** [comment]
ENV variables for backend

clientSecret - generated from the google+ API for user google oauth
clientID - generated from the google+ API for user google oauth
jwtSecret - used for JWT authentication - random string of your choice
dbURI - mongodb database url you want to connect to
AdminclientID  - generated from the google+ API for Organizer google oauth
AdminclientSecret - generated from the google+ API for user Organizer oauth
SendgridAPIKey - Generated from sendgrid to send emails
sendgridEmail - the email you will be using to send mails via sendgrid
reCaptchaSecret - generated from google recaptcha site for recaptcha verification


To get the client id, client secret for both user and admin go to - [console.developers.google.com]() and make 2 different projects.

For sendgrid key go to - [sendgrid.com]()

For recaptcha go to - [google.com/recaptcha]()

For dbURI got to - [mongodb.com]()



Create a .env file in the root with all these variables, make sure you keep the same casing.


If anything doesn't make sense, do send me a mail on jugalbhatt3@gmail.com and we can work this in some other manner.
